server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringSecurity
    username: postgres
    password: ipsitadas
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: productcoupon
  thymeleaf:
    cache: false