spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringSecurity?currentSchema=eazybank
    username: postgres
    password: ipsitadas
    hikari:
      schema: eazybank
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: eazybank

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG