server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringSecurity
    username: postgres
    password: ipsitadas
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: productcoupon

couponService:
  url: http://localhost:8080/couponapi/coupons/